
- ros_topic_name: "/f450b/imu"                # Tópico en ROS 2
  gz_topic_name: "/imu"                      # Tópico en Gazebo
  ros_type_name: "sensor_msgs/msg/Imu"       # Tipo de mensaje en ROS 2 para IMU
  gz_type_name: "gz.msgs.IMU"                # Tipo de mensaje en Gazebo para IMU
  direction: GZ_TO_ROS  # Dirección de los mensajes, en este caso de Gazebo a ROS

- ros_topic_name: "/gazebo/command/motor_speed"      # Tópico en ROS2 para el control de los motores
  gz_topic_name: "/f450b/gazebo/command/motor_speed"
  ros_type_name: "actuator_msgs/msg/Actuators"                 # Tipo de mensaje en ROS2
  gz_type_name: "gz.msgs.Actuators"                  # Tipo de mensaje en Gazebo
  direction: ROS_TO_GZ                              # Dirección de los mensajes (de ROS a Gazebo)

- ros_topic_name: "/gazebo/command/twist"       # Tópico en ROS 2 desde el cual publicarás comandos de velocidad
  gz_topic_name: "/f450b/gazebo/command/twist"        # Debe coincidir con el <commandSubTopic> del plugin
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ


- ros_topic_name: "/odom"                     # Tópico en ROS 2
  gz_topic_name: "/f450b/odom"                # Tópico en Gazebo
  ros_type_name: "nav_msgs/msg/Odometry"      # Tipo de mensaje en ROS 2 para Odometry
  gz_type_name: "gz.msgs.Odometry"            # Tipo de mensaje en Gazebo para Odometry
  direction: GZ_TO_ROS                        # Dirección de los mensajes, en este caso de Gazebo a ROS 2